export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST"
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"

export const FETCH_SINGLE_BOOK_REQUEST = "FETCH_SINGLE_BOOK_REQUEST"
export const FETCH_SINGLE_BOOK_SUCCESS = "FETCH_SINGLE_BOOK_SUCCESS"
export const FETCH_SINGLE_BOOK_FAILURE = "FETCH_SINGLE_BOOK_FAILURE"
