export const ADD_TO_CART = "ADD_TO_CART"

export const PURCHASE_REQUEST = "PURCHASE_REQUEST"
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS"
export const PURCHASE_FAILURE = "PURCHASE_FAILURE"

export default {
  ADD_TO_CART,
  PURCHASE_REQUEST,
  PURCHASE_SUCCESS,
  PURCHASE_FAILURE
}
